Fixes. Testing ok with wildcard.

diff --git a/do-letsencrypt b/do-letsencrypt
--- a/do-letsencrypt
+++ b/do-letsencrypt
@@ -28,6 +28,8 @@ CONFIGPARSE="${SCRIPTDIR}/includes/config_parse"
 function main {
     local FQDN 
     . "$CONFIGPARSE"
+    ansible_check_host "$1" ] 
+    [ $? -eq 1 ] && ansible_add_host "$1"
     letsencrypt_ansible "$1"
     connection_test "$1"
     echo "
@@ -37,7 +39,7 @@ function main {
     "
 }
 
-function provision_ansible {
+function letsencrypt_ansible {
     . "$CONFIGPARSE"
     ansible-playbook "${SCRIPTDIR}/ansible/letsencrypt.yml" --extra-vars "
         host=${HOSTNAME}
@@ -71,36 +73,26 @@ function connection_test {
     done
 }
 
-function ansible_add_host {
-    local DROPLETADDR OLDIP HOSTPATTERN
+function ansible_check_host {
+    local DROPLETADDR HOSTPATTERN ANSIBLEHOSTS
     . "$CONFIGPARSE"
-    DROPLETADDR="$2"
     HOSTPATTERN="^${HOSTNAME} "
-    TMP="/tmp/do-new-wp"
-    [ ! -d "$TMP" ] && mkdir "$TMP"
-    trap "rm -rf ${TMP}" EXIT	
-
-    if grep "$HOSTPATTERN" "${ANSIBLEHOSTS}"; then
-        echo "/n"
-        read -p "${HOSTNAME} was found in ${ANSIBLEHOSTS}, update it with new IP? (y/n)" -n 1 -r
-        echo "/n"
-        if [[ $REPLY =~ ^[Yy]$ ]]; then
-            echo "Changing IP for $HOSTNAME in $ANSIBLEHOSTS"
-            OLDIP=$(grep "$HOSTPATTERN" $ANSIBLEHOSTS | cut -d'=' -f3)
-            [ ! $? -eq 0 ] && return 1
-            sed "s/${OLDIP}/${DROPLETADDR}/g" "$ANSIBLEHOSTS" > "${TMP}/anshosts"
-            cat "${TMP}/anshosts" > "$ANSIBLEHOSTS"
-            [ ! $? -eq 0 ] && return 1
-        elif [[ $REPLY =~ ^[Nn]$ ]]; then
-            echo "Cancelled due to user request"
-            return 0
-        else
-            return 1
-        fi
+    if grep -q "$HOSTPATTERN" "${ANSIBLEHOSTS}"; then
+        echo "${HOSTNAME} was found in ${ANSIBLEHOSTS}"
+        return 0
     else
-        echo "${HOSTNAME} ansible_port=22 ansible_host=${DROPLETADDR}" >> "${ANSIBLEHOSTS}"
-        [ ! $? -eq 0 ] && return 1
+        echo "${HOSTNAME} was not found in ${ANSIBLEHOSTS}"
+        return 1
     fi
+}
+
+function ansible_add_host {
+    local DROPLETADDR HOSTPATTERN ANSIBLEHOSTS
+    . "$CONFIGPARSE"
+    HOSTPATTERN="^${HOSTNAME} "
+    echo "Adding ${HOSTNAME} to ${ANSIBLEHOSTS}"
+    echo "${HOSTNAME} ansible_port=22 ansible_host=${DROPLETADDR}" >> "${ANSIBLEHOSTS}"
+    [ ! $? -eq 0 ] && return 1
     return 0
 }
 
