Restore from restic, partially testing ok

diff --git a/do-new-wp b/do-new-wp
--- a/do-new-wp
+++ b/do-new-wp
@@ -24,6 +24,11 @@ Optional vars and their default values:
     IMAGE ubuntu-16-04-x64
     REGION sfo2
     WPUSER admin
+
+Optional vars with no defaults.
+Set these to trigger related feature.
+    RESTICCODEBASE hash of target snapshot to restore
+    RESTICDB hash of target db to restore
 "
     exit 1
 fi
@@ -40,6 +45,7 @@ fi
 FQDN="${SUBDOMAIN}.${DOMAIN}"
 ADMINIP="$(ifconfig | grep -A 1 'eth0' | tail -1 | cut -d ':' -f 2 | cut -d ' ' -f 1)"
 SCRIPTDIR=$(dirname "${0}")
+RESTIC="/usr/local/bin/restic"
 # Set default values for optional variables
 SSHHOSTS=${SSHHOSTS:-~/.ssh/config}
 ANSHOSTS=${ANSHOSTS:-/etc/ansible/hosts}
@@ -48,6 +54,7 @@ SIZE=${SIZE:-s-1vcpu-1gb}
 IMAGE=${IMAGE:-ubuntu-16-04-x64}
 REGION=${REGION:-sfo2}
 WPUSER=${WPUSER:-admin}
+MOUNTPOINT="${HOME}/.tmp-mount-do"
 # Generate db passwords
 MYSQLROOTPASSWORD=$(tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 18 | head -n 1)
 echo "$MYSQLROOTPASSWORD"
@@ -202,11 +209,11 @@ done
 # Run ansible playbook to set up servers
 cd "${SCRIPTDIR}/ansible"
 ansible-playbook wordpress.yml --extra-vars "
-        mysql_root_password=${MYSQLROOTPASSWORD}
-        mysql_wp_password=${MYSQLWPPASSWORD}
-        fqdn=${FQDN}
-        email=${EMAIL}
-        --limit ${NAME}"
+    mysql_root_password=${MYSQLROOTPASSWORD}
+    mysql_wp_password=${MYSQLWPPASSWORD}
+    fqdn=${FQDN}
+    email=${EMAIL}
+    --limit ${NAME}"
 
 # Run wordpress-install new / clone repo
 cd "${SCRIPTDIR}"
@@ -217,8 +224,11 @@ wordpress-install \
     "${EMAIL}" \
     "${MYSQLWPPASSWORD}"
 
+# Preserve the fresh config file
+ssh "${NAME}" "cp /var/www/html/wp-config.php /var/www/wp-config.php.fresh"
 # Change webroot permissions
-ssh "${NAME}" "chown -R www-data:www-data /var/www/html"
+ssh "${NAME}" "chown -R www-data:www-data /var/www"
+
 
 # Offer to delete the droplet
 doctl compute droplet delete "$DID"
@@ -229,5 +239,36 @@ Wordpress mysql password: ${MYSQLWPPASSWORD}
 Test your new site at:
 https://${FQDN}
 "
+# Optionally restore a site from restic
+# If variable not set then exit without error
+[ -z "$RESTICCODEBASE" ] && exit 0
+if [ -f ~/.wp-admin ]; then
+    # Check for required values and binaries
+    [ ! -f "$RESTIC" ] && { echo "RESTIC binary not found"; exit 1; }
+    [ -z "$RESTICDB" ] && { echo "RESTICDB key not set"; exit 1; }
+    [ -z "$RESTIC_REPOSITORY" ] && { echo "RESTIC_REPOSITORY key not set"; exit 1; }
+    [ -z "$RESTIC_PASSWORD" ] && { echo "RESTIC_PASSWORD key not set"; exit 1; }
+    [ -z "$AWS_ACCESS_KEY_ID" ] && { echo "AWS_ACCESS_KEY_ID key not set"; exit 1; }
+    [ -z "$AWS_SECRET_ACCESS_KEY" ] && { echo "AWS_SECRET_ACCESS_KEY key not set"; exit 1; }
+    source $HOME/.wp-admin
+    # Mount the remote directory on the local server
+    mkdir "${MOUNTPOINT}" || exit 1
+    ssh ${NAME} "mkdir /var/www/new" || exit 1
+    sshfs ${NAME}:/var/www/new "${MOUNTPOINT}" || exit 1
+    # Restore the targeted snapshots to the mount point
+    $RESTIC restore ${RESTICCODEBASE} -t ${MOUNTPOINT} || exit 1
+    $RESTIC restore ${RESTICDB} -t /tmp || exit 1
+    # Replace the webroot with the new files
+    ssh ${NAME} "mv /var/www/html /var/www/html-backup-${USER}" || exit 1
+    ssh ${NAME} "mv /var/www/new /var/www/html" || exit 1
+    ssh ${NAME} "cp /var/www/wp-config.php.fresh /var/www/html/wp-config.php" || exit 1
+    # Extract and import the db
+    cd /tmp
+    gunzip "${NAME}.sql.gz"
+    wordpress-restore-db "${HOST}" tmp
+else
+    notify-critical \
+        "Restic variables, binary or ~/.wp-admin config file not found for ${USER}@${HOSTNAME}, restore to ${FQDN} is not happening (do-new-wp)."
+fi
 
 exit 0
