Fixing playbook, testing if droplet booted. Tests ok.

diff --git a/do-new-wp b/do-new-wp
--- a/do-new-wp
+++ b/do-new-wp
@@ -20,8 +20,6 @@ IMAGE ubuntu-16-04-x64
 REGION sfo2
 "
     exit 1
-    else
-        echo "Provisioning new droplet for ${NAME}"
 fi
 # Include the config file
 . $1
@@ -46,6 +44,7 @@ if grep -w ${NAME} ${SSHHOSTS}; then
 fi
 
 # Provision the droplet
+echo "Provisioning new droplet for ${NAME}"
 DID=$(doctl compute droplet create \
     ${NAME} \
     -o json \
@@ -68,11 +67,13 @@ fi
 
 # Get IP from DO
 # and remove dbl quotes from string
+echo "Getting IP from droplet ${DID}"
 DIP=$(doctl compute droplet get ${DID} -t ${DOTOKEN} -o json \
     | jq '.[0] .networks.v4[0].ip_address' | tr -d '\n')
 DIP=$(echo "$DIP" | tr -d '"')
 
 # Setup ssh config file
+echo "Adding ${NAME} to ssh config file."
 echo "Host ${NAME}
     HostName ${DIP}
     User root
@@ -90,10 +91,21 @@ if [ ! $? -eq 0 ]; then
 fi
 
 echo "Wait for the droplet to boot..."
-sleep 45
+sleep 10
+while true; do
+    ssh -o ConnectTimeout=3 -q ${NAME} exit
+    if [ $? -eq 0 ]; then
+        sleep 3
+        break
+    fi
+done
 
-echo "Install python to support ansible"
-ssh ${NAME} "apt-get -y install python"
+echo "Install python to support ansible, ssl-cert for snakeoil."
+ssh ${NAME} "apt-get -y install python ssl-cert"
+if [ ! $? -eq 0 ]; then
+    echo "Error installing python."
+    exit 1
+fi
 
 # Run ansible playbook to set up servers
 cd ${SCRIPTDIR}/ansible
