Reverting function to inline code. Do not return values in a bash function.

diff --git a/do-new-wp b/do-new-wp
--- a/do-new-wp
+++ b/do-new-wp
@@ -105,14 +105,34 @@ function main {
         echo "Droplet ID is empty."
         exit 1
     else
-        echo "Wait five seconds for the droplet to be created..."
+        echo "Wait five seconds for the IP to become available....."
         sleep 5
     fi
+# This was such a good idea
+    trap "doctl compute droplet delete ${DID}; sleep 3; doctl compute droplet list" EXIT
+# Get IP
+    DIPRAW=$(doctl compute droplet \
+        get "${DID}" \
+        -t "${DOTOKEN}" \
+        -o json) 
+    if [ ! $? -eq 0 ]; then
+        echo "Error retrieving droplet IP address."
+        exit 1
+    fi
+    DIPRAW=$(echo "${DIPRAW}" | jq '.[0] .networks.v4[0].ip_address')
+    if [ ! $? -eq 0 ]; then
+        echo "Error parsing JSON."
+        exit 1
+    fi
+    DIP=$(echo "${DIPRAW}" | tr -d '\n' | tr -d '"')
+    if [ -z "$DIP" ]; then
+        echo "IP address is empty?"
+        exit 1
+    fi
 # Get IP, setup SSH and Ansible config, create DNS A record
-    DIP=$(droplet_get_ip "$DID" "$DOTOKEN")
-    ssh_config_add_host "$NAME" "$SSHHOSTS" "$DIP" "$PATHTOPRIVKEY"
-    ansible_add_host "$NAME" "$ANSHOSTS" "$DIP"
-    do_add_record "$SUBDOMAIN" "$DOMAIN" "$DIP"
+    ssh_config_add_host "$NAME" "$SSHHOSTS" "$DIP" "$PATHTOPRIVKEY" || exit 2
+    ansible_add_host "$NAME" "$ANSHOSTS" "$DIP" || exit 2
+    do_add_record "$SUBDOMAIN" "$DOMAIN" "$DIP" || exit 2
 # Wait for the new droplet to become ready
     echo -ne "Wait for the droplet initialisation to complete..."
     while true; do
@@ -179,34 +199,6 @@ function main {
     Test your new site at:
     https://${FQDN}
     "
-}
-
-function droplet_get_ip {
-    local DID DOTOKEN DIPRAW DIP
-    DID="$1"
-    DOTOKEN="$2"
-    echo "Getting IP from droplet ${DID}."
-    DIPRAW=$(doctl compute droplet \
-        get "${DID}" \
-        -t "${DOTOKEN}" \
-        -o json) 
-    if [ ! $? -eq 0 ]; then
-        echo "Error retrieving droplet IP address."
-        echo "${DIPRAW}"
-        exit 1
-    fi
-    DIPRAW=$(echo "${DIPRAW}" | jq '.[0] .networks.v4[0].ip_address')
-    if [ ! $? -eq 0 ]; then
-        echo "Error parsing JSON."
-        echo "${DIPRAW}"
-        exit 1
-    fi
-    DIP=$(echo "${DIPRAW}" | tr -d '\n' | tr -d '"')
-    if [ -z "$DIP" ]; then
-        echo "IP address is empty?"
-        exit 1
-    fi
-    echo "$DIP"
 }
 
 function ssh_config_add_host {
