Ansible integration, testing partially ok

diff --git a/do-new-wp b/do-new-wp
--- a/do-new-wp
+++ b/do-new-wp
@@ -20,6 +20,8 @@ IMAGE ubuntu-16-04-x64
 REGION sfo2
 "
     exit 1
+    else
+        echo "Provisioning new droplet for ${NAME}"
 fi
 # Include the config file
 . $1
@@ -46,8 +48,9 @@ fi
 # Provision the droplet
 DID=$(doctl compute droplet create \
     ${NAME} \
-    -t ${DOTOKEN} \
     -o json \
+    -t ${DOTOKEN} \
+    --ssh-keys ${PUBLICKEY} \
     --size ${SIZE} \
     --image ${IMAGE} \
     --region ${REGION} \
@@ -55,8 +58,13 @@ DID=$(doctl compute droplet create \
     --enable-monitoring \
     | jq '.[0] .id' | tr -d '\n')
 
-echo "Wait five seconds for the droplet to be created..."
-sleep 5
+if [ ! $? -eq 0 ]; then
+    echo "Error provisioning droplet"
+    exit 1
+else
+    echo "Wait five seconds for the droplet to be created..."
+    sleep 5
+fi
 
 # Get IP from DO
 # and remove dbl quotes from string
@@ -81,11 +89,18 @@ if [ ! $? -eq 0 ]; then
     exit 1
 fi
 
+echo "Wait for the droplet to boot..."
+sleep 45
+
+echo "Install python to support ansible"
+ssh ${NAME} "apt-get -y install python"
+
 # Run ansible playbook to set up servers
 cd ${SCRIPTDIR}/ansible
 ansible-playbook wordpress.yml --extra-vars "
-    host=${NAME} 
-    mysql_root_password=${MYSQLROOTPASSWORD}"
+        mysql_root_password=${MYSQLROOTPASSWORD}
+        fqdn=${FQDN}
+        --limit ${NAME}"
 
 # Run wordpress-install new / clone repo
 
