Major refactor

diff --git a/do-wp-new b/do-wp-new
--- a/do-wp-new
+++ b/do-wp-new
@@ -39,31 +39,65 @@ if [ $# -eq 0 ]; then
 fi
 
 function main {
-###
-### VARIABLES ###
-###
-    local FQDN ADMINIP SCRIPTDIR RESTIC WPUSER MOUNTPOINT MYSQLROOTPASSWORD
+    local NAME CODEBASE DB RESTICCODEBASE RESTICDB
+    local DOMAIN SUBDOMAIN FQDN SSHHOSTS
+    # Include the config file
+    . "$1"
+
+    [ -z "$NAME" ] && { echo "NAME not set"; exit 1; }
+    [ -z "$DOMAIN" ] && { echo "DOMAIN not set"; exit 1; }
+    [ -z "$SUBDOMAIN" ] && SUBDOMAIN=${NAME}
+    FQDN="${SUBDOMAIN}.${DOMAIN}"
+    SSHHOSTS=${SSHHOSTS:-~/.ssh/config}
+
+    # If host exists then offer to overwrite
+    ssh_config_check "$NAME" "$SSHHOSTS"
+    if [ $? -eq 1 ]; then
+        wp_restore "$1" "$FQDN"
+        exit $?
+    fi
+
+    do_provision "$1"
+
+    # Optionally restore a site to new droplet
+    if [ ! -z "$DB" ] \
+        || [ ! -z "$RESTICDB" ]; then
+        wp_restore "$1" "$FQDN"
+    fi
+
+    echo "
+    ***
+
+    https://${FQDN}
+
+    ***
+    "
+}
+
+
+# Provision a new droplet and install wordpress
+function do_provision {
+    local FQDN ADMINIP SCRIPTDIR WPUSER MYSQLROOTPASSWORD
     local SSHHOSTS ANSHOSTS PATHTOPRIVKEY DROPLETSIZE IMAGE REGION MYSQLWPPASSWORD
     local DIDRAW DID DIP TMP WILDCARDCHAIN NEWCERT
-# Include the config file
+    # Include the config file
     . "$1"
-# TODO add ses creds
-# Check that required variables are set
+    # TODO add ses creds
+    # Check that required variables are set
     [ -z "$NAME" ] && { echo "NAME not set"; exit 1; }
     [ -z "$DOMAIN" ] && { echo "DOMAIN not set"; exit 1; }
     [ -z "$SUBDOMAIN" ] && SUBDOMAIN=${NAME}
     [ -z "$EMAIL" ] && { echo "EMAIL not set"; exit 1; }
     [ -z "$DOTOKEN" ] && { echo "DOTOKEN not set"; exit 1; }
     [ -z "$PUBLICKEY" ] && { echo "PUBLICKEY not set"; exit 1; }
-    FQDN="${SUBDOMAIN}.${DOMAIN}"
     [ -z "$ELASTICSEARCH" ] && ELASTICSEARCH=false
     [ -z "$WILDCARD" ] && WILDCARD=true
     [ "$WILDCARD" ] && NEWCERT=false || NEWCERT=true
     [ "$WILDCARD" ] && WILDCARDCHAIN="/etc/letsencrypt/archive/${DOMAIN}" || echo "Wildcard not set"
     ADMINIP="$(ifconfig | grep -A 1 'eth0' | tail -1 | cut -d ':' -f 2 | cut -d ' ' -f 1)"
+    FQDN="${SUBDOMAIN}.${DOMAIN}"
     SCRIPTDIR=$(dirname "${0}")
-    RESTIC="/usr/local/bin/restic"
-# Set default values for optional variables
+    # Set default values for optional variables
     SSHHOSTS=${SSHHOSTS:-~/.ssh/config}
     ANSHOSTS=${ANSHOSTS:-/etc/ansible/hosts}
     PATHTOPRIVKEY=${PATHTOPRIVKEY:-~/.ssh/id_rsa}
@@ -71,19 +105,21 @@ function main {
     IMAGE=${IMAGE:-ubuntu-16-04-x64}
     REGION=${REGION:-sfo2}
     WPUSER=${WPUSER:-admin}
-    MOUNTPOINT="${HOME}/.tmp-mount-do"
-# Generate db passwords
+    # Generate db passwords
     MYSQLROOTPASSWORD=$(tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 18 | head -n 1)
     MYSQLWPPASSWORD=$(tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 18 | head -n 1)
-# Setup a tmp dir
+    # Setup a tmp dir
     TMP="/tmp/do-new-wp"
     [ ! -d "$TMP" ] && mkdir "$TMP"
-# Cleanup on exit
+    # Cleanup on exit
     trap "rm -rf ${TMP}" EXIT	
 
-###
-### PROVISION ###
-###
+    #if [ $(ssh_config_check "$NAME" "$SSHHOSTS") ]; then
+        # add nonce
+        # repeat until no conflicts
+    #fi
+
+    # Provision the droplet and store its ID
     echo "Provisioning new droplet for ${NAME}."
     DIDRAW=$(doctl compute droplet create \
         "$NAME" \
@@ -115,9 +151,9 @@ function main {
         echo "Wait three seconds for the IP to become available....."
         sleep 3
     fi
-# This was such a good idea
+    # Offer to delete droplet on exit
     trap "doctl compute droplet delete -t ${DOTOKEN} ${DID}; sleep 3; doctl compute droplet list -t ${DOTOKEN}" EXIT
-# Get IP
+    # Get IP
     while true; do
         DIPRAW=$(doctl compute droplet \
             get "${DID}" \
@@ -141,31 +177,16 @@ function main {
             break
         fi
     done
-# Get IP, setup SSH and Ansible config, create DNS A record
+    # Get IP, setup SSH and Ansible config, create DNS A record
     ssh_config_add_host "$NAME" "$SSHHOSTS" "$DIP" "$PATHTOPRIVKEY" \
         || { echo "ssh config error $?"; exit 2; }
     ansible_add_host "$NAME" "$ANSHOSTS" "$DIP" \
         || { echo "ansible config error $?"; exit 2; }
     do_add_record "$SUBDOMAIN" "$DOMAIN" "$DIP" \
         || { echo "dns config error $?"; exit 2; }
-# Wait for the new droplet to become ready
-    echo -ne "Wait for the droplet initialisation to complete..."
-    while true; do
-        ssh -o ConnectTimeout=3 -q "${NAME}" \
-            "[ -f /var/lib/cloud/instance/boot-finished ]"
-        if [ $? -eq 0 ]; then
-            sleep 1
-            echo -ne "\r"
-            break
-        else
-            echo -ne "."
-            sleep 1
-        fi
-    done
+    connection_test "$NAME"
 
-###
 ### INSTALL SOFTWARE ###
-###
     echo "Install prerequisite packages."
     while true; do
         ssh -o ConnectTimeout=3 "${NAME}" \
@@ -182,6 +203,7 @@ function main {
         echo "Error installing wp-cli."
         exit 1
     fi
+
 # Run ansible playbook to set up servers
     cd "${SCRIPTDIR}/ansible"
     ansible-playbook wordpress.yml --extra-vars "
@@ -201,6 +223,7 @@ function main {
         echo "Error running ansible."
         exit 1
     fi
+
 # Run wordpress-install new / clone repo
     cd "${SCRIPTDIR}"
     wordpress-install \
@@ -219,76 +242,85 @@ function main {
         echo "Error copying config file."
         exit 1
     fi
+
 # Change webroot permissions
     wordpress-permissions "$NAME" dev
     if [ ! $? -eq 0 ]; then
         echo "Error setting permissions."
         exit 1
     fi
-
-# Optionally restore a site from local
-    if [ ! -z "$CODEBASE" ]; then
-        do-wp-restore-local "$NAME" "$FQDN" "$DB" "$CODEBASE"
-    fi
-# Optionally restore a site from restic
-    if [ -f ~/.wp-admin ] && [ ! -z "$RESTICCODEBASE" ]; then
-        do-wp-restore-restic "$NAME" "$FQDN" "$RESTICDB" "$RESTICCODEBASE"
-    fi
-
-###
-### END OF MAIN ###
-###
-    echo "
-    ***
-
-    https://${FQDN}
-
-    $ANSHOSTS has been modified.
-    $SSHHOSTS has been modified.
-
-    Root mysql password: ${MYSQLROOTPASSWORD}
-    Wordpress mysql password: ${MYSQLWPPASSWORD}
-    Droplet ID: ${DID}
-    Droplet IP Address: ${DIP}
-
-    ***
-    "
 }
 
+# Optionally run a restoration
+function wp_restore {
+    local NAME FQDN DB CODEBASE RESTICDB RESTICCODEBASE
+    CONFIG="$1"
+    FQDN="$2"
+    . "$CONFIG"
+    if [ ! -z "$CODEBASE" ]; then
+        read -p "Restore ${CODEBASE} to ${NAME}? (y/n)" -n 1 -r
+        echo "/n"
+        if [[ $REPLY =~ ^[Yy]$ ]]; then
+            do-wp-restore-local "$NAME" "$FQDN" "$DB" "$CODEBASE"
+        else
+            return 1
+        fi
+    elif [ -f ~/.wp-admin ] && [ ! -z "$RESTICCODEBASE" ]; then
+        read -p "Restore restic snapshot ${RESTICCODEBASE} to ${NAME}? (y/n)" -n 1 -r
+        echo "/n"
+        if [[ $REPLY =~ ^[Yy]$ ]]; then
+            do-wp-restore-restic "$NAME" "$FQDN" "$RESTICDB" "$RESTICCODEBASE"
+        else
+            return 1
+        fi
+    fi
+}
+
+# Wait for the new droplet to become ready
+function connection_test {
+    local NAME
+    NAME="$1"
+    echo -ne "Wait for the droplet to become available..."
+    while true; do
+        ssh -o ConnectTimeout=3 -q "${NAME}" \
+            "[ -f /var/lib/cloud/instance/boot-finished ]"
+        if [ $? -eq 0 ]; then
+            sleep 1
+            echo -ne "\r"
+            break
+        else
+            echo -ne "."
+            sleep 1
+        fi
+    done
+}
+
+function ssh_config_check {
+    local NAME SSHHOSTS HOSTPATTERN
+    NAME="$1"
+    SSHHOSTS="$2"
+    HOSTPATTERN="^Host ${NAME}$"
+    if grep "$HOSTPATTERN" "${SSHHOSTS}"; then
+        grep "$HOSTPATTERN" -A5 "${SSHHOSTS}"
+        echo "${NAME} was found in ${SSHHOSTS}"
+        connection_test "$NAME"
+        return 1
+    else
+        return 0
+    fi
+}
 function ssh_config_add_host {
-    local NAME SSHHOSTS DIP PATHTOPRIVKEY OLDIP HOSTPATTERN
+    local NAME SSHHOSTS DIP PATHTOPRIVKEY
     NAME="$1"
     SSHHOSTS="$2"
     DIP="$3"
     PATHTOPRIVKEY="$4"
-    HOSTPATTERN="^Host ${NAME}$"
-    if grep "$HOSTPATTERN" "${SSHHOSTS}"; then
-        grep "$HOSTPATTERN" -A5 "${SSHHOSTS}"
-        read -p "${NAME} was found in ${SSHHOSTS}, update it with new IP? (y/n)" -n 1 -r
-        echo
-        if [[ $REPLY =~ ^[Yy]$ ]]; then
-            echo "Changing IP for $NAME in $SSHHOSTS"
-            OLDIP=$(grep -A1 "$HOSTPATTERN" "$SSHHOSTS" | tail -n1 | cut -d' ' -f6)
-            [ ! $? -eq 0 ] && { echo "grep error $?"; return 1; }
-            [ -z "$OLDIP" ] && { echo "oldip is empty"; return 1; }
-            sed -i "s/${OLDIP}/${DIP}/g" "$SSHHOSTS"
-            [ ! $? -eq 0 ] && { echo "sed error $?" ; return 1; }
-        elif [[ $REPLY =~ ^[Nn]$ ]]; then
-            echo "Cancelled due to user request"
-            return 0
-        else
-            return 1
-        fi
-    else
-        echo "Host ${NAME}
+    echo "Host ${NAME}
     HostName ${DIP}
     User root
     IdentityFile ${PATHTOPRIVKEY}
     IdentitiesOnly yes
-        " >> "${SSHHOSTS}"
-        [ ! $? -eq 0 ] && return 1
-    fi
-    return 0
+    " >> "${SSHHOSTS}"
 }
 
 function ansible_add_host {
