Big messy commit. Elasticsearch, different ufw role. Improve permissions script.

diff --git a/do-wp-new b/do-wp-new
--- a/do-wp-new
+++ b/do-wp-new
@@ -201,9 +201,17 @@ function main {
         exit 1
     fi
 # Preserve the fresh config file
-    ssh "${NAME}" "cp /var/www/html/wp-config.php /var/www/wp-config.php.fresh" || exit 1
+    ssh "${NAME}" "cp /var/www/html/wp-config.php /var/www/wp-config.php.fresh"
+    if [ ! $? -eq 0 ]; then
+        echo "Error copying config file."
+        exit 1
+    fi
 # Change webroot permissions
-    wordpress-permissions "$NAME" dev || exit 1
+    wordpress-permissions "$NAME" dev
+    if [ ! $? -eq 0 ]; then
+        echo "Error setting permissions."
+        exit 1
+    fi
 
 # Optionally restore a site from local
     if [ ! -z "$CODEBASE" ]; then
