Add screenshot to post-restoration notification

diff --git a/notify b/notify
--- a/notify
+++ b/notify
@@ -34,13 +34,13 @@ if [ ! $? -eq 0 ]; then
 	echo "$(date) ${MESSAGE}"
 	exit 1
 fi
-if [ $SINCELASTRUN -lt 11 ]; then
-	echo "$(date) ${SINCELASTRUN}s since last post. Please wait until 10s have passed. Aborting."
-	echo "$(date) ${MESSAGE}"
-	exit 1
-else
-	echo $(date +%s) > "$LASTRUNFILE"
-fi
+#if [ $SINCELASTRUN -lt 11 ]; then
+#	echo "$(date) ${SINCELASTRUN}s since last post. Please wait until 10s have passed. Aborting."
+#	echo "$(date) ${MESSAGE}"
+#	exit 1
+#else
+#	echo $(date +%s) > "$LASTRUNFILE"
+#fi
 
 screenshot() {
 	local TEMPDIR TEMPURL TEMPPIC URL PARGS MID
