Replace tabs with spaces

diff --git a/os-le-lsws b/os-le-lsws
--- a/os-le-lsws
+++ b/os-le-lsws
@@ -11,28 +11,28 @@ Env variable LEMAIL must be set
 "
 # Print USAGE if no args
 if [ $# -lt 1 ] ||
-	[ -z $LEMAIL ] ; then
-	echo "$USAGE"
-	exit 1
+    [ -z $LEMAIL ] ; then
+    echo "$USAGE"
+    exit 1
 fi
 HOST=$1
 if [ -z $2 ]; then
-	WWW="www.$HOST"
+    WWW="www.$HOST"
 fi
 
 # Connection test
 ssh $HOST "exit 0"
 if [ ! $? -eq 0 ]; then
-	echo "FAIL to connect to $HOST over ssh"
-	exit 2
+    echo "FAIL to connect to $HOST over ssh"
+    exit 2
 fi
 
 # Verify what certs are being used
 # Fail if the configured cert path does not match our expectation
 ssh ${HOST} "grep -q $HOST/fullchain.pem /usr/local/lsws/conf/vhosts/wordpress/vhconf.conf"
 if [ ! $? -eq 0 ]; then
-	echo "FAIL to find expected cert path in config"
-	exit 2
+    echo "FAIL to find expected cert path in config"
+    exit 2
 fi
 echo "Expected configuration was found."
 
@@ -42,48 +42,48 @@ echo "Expected configuration was found."
 
 # Run certbot in test mode to verify domain resolution
 CMD="certbot certonly \
-	--dry-run \
-	--non-interactive \
-	--force-renew \
-	--email=$LEMAIL \
-	--agree-tos \
-	--authenticator=standalone \
-	--pre-hook='/bin/systemctl stop lsws; sleep 5' \
-	--post-hook='/bin/systemctl start lsws' \
-	-d $HOST"
+    --dry-run \
+    --non-interactive \
+    --force-renew \
+    --email=$LEMAIL \
+    --agree-tos \
+    --authenticator=standalone \
+    --pre-hook='/bin/systemctl stop lsws; sleep 5' \
+    --post-hook='/bin/systemctl start lsws' \
+    -d $HOST"
 if [ ! -z $WWW ]; then
-	CMD+=" -d $WWW"
+    CMD+=" -d $WWW"
 fi
 # -t makes it an interactive session, output is verbose
 ssh -t ${HOST} ${CMD}
 if [ ! $? -eq 0 ]; then
-	echo "FAIL certbot dry run"
-	exit 2
+    echo "FAIL certbot dry run"
+    exit 2
 fi
 CMD=""
 
 # BACKUP the old certs for this domain
 ssh ${HOST} "cp -rf /etc/letsencrypt ~/BACKUP-LE-$(date +%s)"
 if [ ! $? -eq 0 ]; then
-	echo "FAIL to backup old certs"
-	exit 2
+    echo "FAIL to backup old certs"
+    exit 2
 fi
 
 # DELETE the old certs for this domain
 ssh ${HOST} "rm -rf /etc/letsencrypt/live/$HOST"
 if [ ! $? -eq 0 ]; then
-	echo "FAIL to remove old certs"
-	exit 2
+    echo "FAIL to remove old certs"
+    exit 2
 fi
 ssh ${HOST} "rm -rf /etc/letsencrypt/archive/$HOST" 
 if [ ! $? -eq 0 ]; then
-	echo "FAIL to remove old certs"
-	exit 2
+    echo "FAIL to remove old certs"
+    exit 2
 fi
 ssh ${HOST} "rm /etc/letsencrypt/renewal/$HOST.conf" 
 if [ ! $? -eq 0 ]; then
-	echo "FAIL to remove old certs"
-	exit 2
+    echo "FAIL to remove old certs"
+    exit 2
 fi
 echo "Old certs removed."
 
@@ -94,22 +94,22 @@ echo "Old certs removed."
 #   authenticator = standalone
 echo "Getting the new cert..."
 CMD="certbot certonly \
-	--non-interactive \
-	--force-renew \
-	--email=$LEMAIL \
-	--agree-tos \
-	--authenticator=standalone \
-	--pre-hook='/bin/systemctl stop lsws; sleep 5' \
-	--post-hook='/bin/systemctl start lsws' \
-	-d $HOST"
+    --non-interactive \
+    --force-renew \
+    --email=$LEMAIL \
+    --agree-tos \
+    --authenticator=standalone \
+    --pre-hook='/bin/systemctl stop lsws; sleep 5' \
+    --post-hook='/bin/systemctl start lsws' \
+    -d $HOST"
 if [ ! -z $WWW ]; then
-	CMD+=" -d $WWW"
+    CMD+=" -d $WWW"
 fi
 # -t makes it an interactive session, output is verbose
 ssh -t ${HOST} ${CMD}
 if [ ! $? -eq 0 ]; then
-	echo "FAIL certbot live"
-	exit 2
+    echo "FAIL certbot live"
+    exit 2
 fi
 
 ssh $HOST "reboot"
diff --git a/wordpress-backup b/wordpress-backup
--- a/wordpress-backup
+++ b/wordpress-backup
@@ -6,11 +6,11 @@ Usage: wordpress-backup DOMAIN BACKUPTYPE [WEBROOT]
 Where:
 - DOMAIN must be available in ssh config
 - BACKUPTYPE can be one of:
-	- full: backup webroot and db to s3, rotated
-	- manual: full backup to BACKUP_DIRECTORY_LOCAL/manual and s3, not rotated
-	- db: backup db to admin server
-	- tmp: backup db and webroot to /tmp on admin server
-	- dbtmp: backup db to /tmp on admin server
+    - full: backup webroot and db to s3, rotated
+    - manual: full backup to BACKUP_DIRECTORY_LOCAL/manual and s3, not rotated
+    - db: backup db to admin server
+    - tmp: backup db and webroot to /tmp on admin server
+    - dbtmp: backup db to /tmp on admin server
 - WEBROOT is optional, defaults to /var/www/html
 
 Note: if WEBROOT is not supplied then wordpress-permissions 
@@ -21,32 +21,32 @@ Configure Restic for s3
 =======================
 Create two buckets on s3 with an IAM user for each.
 Create two files in ~/.wp-admin-config/:
-	- restic-full.conf
-	- restic-manual.conf
+    - restic-full.conf
+    - restic-manual.conf
 Each file needs the following environment variables:
-	- export RESTIC_REPOSITORY
-	- export RESTIC_PASSWORD
-	- export AWS_ACCESS_KEY_ID
-	- export AWS_SECRET_ACCESS_KEY
+    - export RESTIC_REPOSITORY
+    - export RESTIC_PASSWORD
+    - export AWS_ACCESS_KEY_ID
+    - export AWS_SECRET_ACCESS_KEY
 Optional environment variables and their default values:
-	- export RESTIC_CACHE='~/.cache/restic'
-	- export BUP_DIR='/var/backups/wordpress'
-	- export BACKUPS_TO_KEEP=28
-	- export RESTIC='/usr/local/bin/restic'
+    - export RESTIC_CACHE='~/.cache/restic'
+    - export BUP_DIR='/var/backups/wordpress'
+    - export BACKUPS_TO_KEEP=28
+    - export RESTIC='/usr/local/bin/restic'
 "
 
 # Print USAGE if no args
 if [ $# -eq 0 ]; then
-	echo "$USAGE"
-	exit 1
+    echo "$USAGE"
+    exit 1
 fi
 # Check if already running
 if ! mkdir -p /tmp/wordpress-backup.lock; then
-	echo "$(date) Failed to acquire lock. (Script already running?)"
-	exit 1
+    echo "$(date) Failed to acquire lock. (Script already running?)"
+    exit 1
 fi
 # Remove the lockdir on exit
-trap 'rm -rf /tmp/wordpress-backup.lock' EXIT	
+trap 'rm -rf /tmp/wordpress-backup.lock' EXIT   
 
 DOMAIN="$1"
 GROUP="mribackup"
@@ -73,182 +73,182 @@ TEASER="${DOMAIN} (${BACKUPTYPE}) at ${SITEURL}"
 WPBIN=$(which wp)
 # Set global options for wp-cli or report missing binary
 if [ $? -eq 0 ]; then
-	WP="${WPBIN} --path=${WEBROOT} --allow-root --skip-themes --skip-plugins --ssh=${DOMAIN}"
+    WP="${WPBIN} --path=${WEBROOT} --allow-root --skip-themes --skip-plugins --ssh=${DOMAIN}"
 else
-	notify "wp-cli not found on admin server" critical
-	exit 1
+    notify "wp-cli not found on admin server" critical
+    exit 1
 fi
 RESTIC_REPOSITORY=""
 RESTIC_PASSWORD=""
 
 restic-check() {
-	if [ -f "$RESTIC" ]; then
-		if [ "$BACKUPTYPE" == "full" ]; then
-			. "${HOME}/.wp-admin-config/restic-full.conf"
-			[ $? -eq 0 ] || { echo "$(date) Missing configuration"; exit 1; }
-		elif [ "$BACKUPTYPE" == "manual" ]; then 
-			. "${HOME}/.wp-admin-config/restic-manual.conf"
-			[ $? -eq 0 ] || { echo "$(date) Missing configuration"; exit 1; }
-		fi
-	else
-		notify \
-			"Restic or wp-admin.conf file not found for ${USER}@${DOMAIN}, backup to s3 for ${DOMAIN} is not happening." critical
-	fi
+    if [ -f "$RESTIC" ]; then
+        if [ "$BACKUPTYPE" == "full" ]; then
+            . "${HOME}/.wp-admin-config/restic-full.conf"
+            [ $? -eq 0 ] || { echo "$(date) Missing configuration"; exit 1; }
+        elif [ "$BACKUPTYPE" == "manual" ]; then 
+            . "${HOME}/.wp-admin-config/restic-manual.conf"
+            [ $? -eq 0 ] || { echo "$(date) Missing configuration"; exit 1; }
+        fi
+    else
+        notify \
+            "Restic or wp-admin.conf file not found for ${USER}@${DOMAIN}, backup to s3 for ${DOMAIN} is not happening." critical
+    fi
 }
 
 wp-check() {
 # TODO check host is accessible over ssh
-	${WP} \
-		--quiet \
-		core is-installed
-	if [ ! $? -eq 0 ]; then
-		notify "${DOMAIN} \
-			WP does not appear to be running. What the heck?" \
-			critical
-		exit 1
-	fi
-	SITEURL=$(${WP} --quiet option get siteurl)
-	if [ ! $? -eq 0 ]; then
-		notify "${DOMAIN} \
-			Error getting siteurl." \
-			critical
-		exit 1
-	fi
-	[ -z "$SITEURL" ] && { echo "$(date) SITEURL is empty."; exit 1; }
+    ${WP} \
+        --quiet \
+        core is-installed
+    if [ ! $? -eq 0 ]; then
+        notify "${DOMAIN} \
+            WP does not appear to be running. What the heck?" \
+            critical
+        exit 1
+    fi
+    SITEURL=$(${WP} --quiet option get siteurl)
+    if [ ! $? -eq 0 ]; then
+        notify "${DOMAIN} \
+            Error getting siteurl." \
+            critical
+        exit 1
+    fi
+    [ -z "$SITEURL" ] && { echo "$(date) SITEURL is empty."; exit 1; }
 }
 
 check-args() {
-	if [ "$DOMAIN" == "full" ] \
-		|| [ "$DOMAIN" == "db" ] \
-		|| [ "$DOMAIN" == "manual" ] \
-		|| [ "$DOMAIN" == "tmp" ]; then
-		notify "Error in first argument, ${DOMAIN} (arg1) ${BACKUPTYPE} (arg 2) backup." critical
-		exit 1
-	fi
-	if [ "$BACKUPTYPE" != "full" ] \
-		&& [ "$BACKUPTYPE" != "db" ] \
-		&& [ "$BACKUPTYPE" != "manual" ] \
-		&& [ "$BACKUPTYPE" != "tmp" ] \
-		&& [ "$BACKUPTYPE" != "dbtmp" ]; then
-		notify "Error in second argument, ${DOMAIN} (arg 1) ${BACKUPTYPE} (arg 2) backup." critical
-		exit 1
-	fi
+    if [ "$DOMAIN" == "full" ] \
+        || [ "$DOMAIN" == "db" ] \
+        || [ "$DOMAIN" == "manual" ] \
+        || [ "$DOMAIN" == "tmp" ]; then
+        notify "Error in first argument, ${DOMAIN} (arg1) ${BACKUPTYPE} (arg 2) backup." critical
+        exit 1
+    fi
+    if [ "$BACKUPTYPE" != "full" ] \
+        && [ "$BACKUPTYPE" != "db" ] \
+        && [ "$BACKUPTYPE" != "manual" ] \
+        && [ "$BACKUPTYPE" != "tmp" ] \
+        && [ "$BACKUPTYPE" != "dbtmp" ]; then
+        notify "Error in second argument, ${DOMAIN} (arg 1) ${BACKUPTYPE} (arg 2) backup." critical
+        exit 1
+    fi
 }
 
 set-backup-dir() {
-	case "$BACKUPTYPE" in
-	"db") 
-		DBFNAME=${DOMAIN}-dbonly.sql
-		;;
-	"manual") 
-		local DATESTAMP=$(date +%F)
-		DBFNAME="${DOMAIN}-${DATESTAMP}.sql"
-		BACKUP_DIRECTORY_LOCAL="${BACKUP_DIRECTORY_LOCAL}/manual"
-		FULLBUPDIR="${BACKUP_DIRECTORY_LOCAL}/${DOMAIN}-${DATESTAMP}"
-		;;
-	"full") 
-		FULLBUPDIR="${BACKUP_DIRECTORY_LOCAL}/${DOMAIN}"
-		;;
-	"tmp") 
-		BACKUP_DIRECTORY_LOCAL="/tmp"
-		FULLBUPDIR="${BACKUP_DIRECTORY_LOCAL}/${DOMAIN}"
-		;;
-	"dbtmp")
-		BACKUP_DIRECTORY_LOCAL="/tmp"
-		;;
-	esac
-	[ ! -d $BACKUP_DIRECTORY_LOCAL ] && mkdir $BACKUP_DIRECTORY_LOCAL
-	cd ${BACKUP_DIRECTORY_LOCAL}
+    case "$BACKUPTYPE" in
+    "db") 
+        DBFNAME=${DOMAIN}-dbonly.sql
+        ;;
+    "manual") 
+        local DATESTAMP=$(date +%F)
+        DBFNAME="${DOMAIN}-${DATESTAMP}.sql"
+        BACKUP_DIRECTORY_LOCAL="${BACKUP_DIRECTORY_LOCAL}/manual"
+        FULLBUPDIR="${BACKUP_DIRECTORY_LOCAL}/${DOMAIN}-${DATESTAMP}"
+        ;;
+    "full") 
+        FULLBUPDIR="${BACKUP_DIRECTORY_LOCAL}/${DOMAIN}"
+        ;;
+    "tmp") 
+        BACKUP_DIRECTORY_LOCAL="/tmp"
+        FULLBUPDIR="${BACKUP_DIRECTORY_LOCAL}/${DOMAIN}"
+        ;;
+    "dbtmp")
+        BACKUP_DIRECTORY_LOCAL="/tmp"
+        ;;
+    esac
+    [ ! -d $BACKUP_DIRECTORY_LOCAL ] && mkdir $BACKUP_DIRECTORY_LOCAL
+    cd ${BACKUP_DIRECTORY_LOCAL}
 }
 
 rotate-db-backups() {
-	local I N FNAME
-	# Trim off the file extension
-	FNAME="${DBFNAME%'.sql'}"
-	echo "$(date) Rotate db backups ($FNAME)."
-	I=$BACKUPS_TO_KEEP
-	while [ $I -gt 0 ]
-	do
-		if [ $I -gt 1 ]; then
-			H=$[I-1]
-			if [ -f ${FNAME}.${H}.sql.gz ]; then
-				mv ${FNAME}.${H}.sql.gz \
-				${FNAME}.${I}.sql.gz \
-				>/dev/null 2>&1
-			fi
-		else
-			if [ -f ${FNAME}.sql.gz ]; then
-				mv ${FNAME}.sql.gz \
-				${FNAME}.1.sql.gz \
-				>/dev/null 2>&1
-			fi
-		fi
-		(( I-- ))
-	done
+    local I N FNAME
+    # Trim off the file extension
+    FNAME="${DBFNAME%'.sql'}"
+    echo "$(date) Rotate db backups ($FNAME)."
+    I=$BACKUPS_TO_KEEP
+    while [ $I -gt 0 ]
+    do
+        if [ $I -gt 1 ]; then
+            H=$[I-1]
+            if [ -f ${FNAME}.${H}.sql.gz ]; then
+                mv ${FNAME}.${H}.sql.gz \
+                ${FNAME}.${I}.sql.gz \
+                >/dev/null 2>&1
+            fi
+        else
+            if [ -f ${FNAME}.sql.gz ]; then
+                mv ${FNAME}.sql.gz \
+                ${FNAME}.1.sql.gz \
+                >/dev/null 2>&1
+            fi
+        fi
+        (( I-- ))
+    done
 }
 
 dump-db() {
-	${WP} db export ${WEBROOT}/../${DBFNAME}
-	if [ ! $? -eq 0  ]; then
-		notify "Database export failed for ${TEASER}" critical
-		exit 1
-	fi
-	ssh ${DOMAIN} "gzip -vf ${WEBROOT}/../${DBFNAME}"
-	if [ ! $? -eq 0  ]; then
-		notify "Backup gzip failed for ${TEASER}" critical
-		exit 1
-	fi
-	scp ${DOMAIN}:${WEBROOT}/../${DBFNAME}.gz .
-	if [ ! $? -eq 0  ]; then
-		notify "DB scp failed for ${TEASER}" critical
-		exit 1
-	fi
+    ${WP} db export ${WEBROOT}/../${DBFNAME}
+    if [ ! $? -eq 0  ]; then
+        notify "Database export failed for ${TEASER}" critical
+        exit 1
+    fi
+    ssh ${DOMAIN} "gzip -vf ${WEBROOT}/../${DBFNAME}"
+    if [ ! $? -eq 0  ]; then
+        notify "Backup gzip failed for ${TEASER}" critical
+        exit 1
+    fi
+    scp ${DOMAIN}:${WEBROOT}/../${DBFNAME}.gz .
+    if [ ! $? -eq 0  ]; then
+        notify "DB scp failed for ${TEASER}" critical
+        exit 1
+    fi
 }
 
 sync-files() {
-	[ ! -d $FULLBUPDIR ] && mkdir $FULLBUPDIR
-	echo "$(date) Sync codebase from ${DOMAIN}"
-	rsync \
-		-qptLr \
-		--exclude=${EXCLUDE} \
-		--delete \
-		${DOMAIN}:${WEBROOT} \
-		${FULLBUPDIR}
-	if [ $? -eq 0 ]; then
-		echo "$(date) Sync from ${DOMAIN} was completed without error"
-	else
-		notify "File sync failed for ${TEASER}" critical
-	fi
-	echo "$(date) Updating permissions on local backup copy"
-	chown "$USER:$GROUP" -R "$FULLBUPDIR" || echo "$(date) ERROR"
-	find "$FULLBUPDIR" -type f -exec chmod 660 {} + || echo "$(date) ERROR"
-	find "$FULLBUPDIR" -type d -exec chmod 770 {} + || echo "$(date) ERROR"
+    [ ! -d $FULLBUPDIR ] && mkdir $FULLBUPDIR
+    echo "$(date) Sync codebase from ${DOMAIN}"
+    rsync \
+        -qptLr \
+        --exclude=${EXCLUDE} \
+        --delete \
+        ${DOMAIN}:${WEBROOT} \
+        ${FULLBUPDIR}
+    if [ $? -eq 0 ]; then
+        echo "$(date) Sync from ${DOMAIN} was completed without error"
+    else
+        notify "File sync failed for ${TEASER}" critical
+    fi
+    echo "$(date) Updating permissions on local backup copy"
+    chown "$USER:$GROUP" -R "$FULLBUPDIR" || echo "$(date) ERROR"
+    find "$FULLBUPDIR" -type f -exec chmod 660 {} + || echo "$(date) ERROR"
+    find "$FULLBUPDIR" -type d -exec chmod 770 {} + || echo "$(date) ERROR"
 }
 
 compress_codebase() {
-	local BASENAME="${FULLBUPDIR##*/}"
-	local DIR="${FULLBUPDIR%/*}"
-	echo "$BASENAME in $DIR"
+    local BASENAME="${FULLBUPDIR##*/}"
+    local DIR="${FULLBUPDIR%/*}"
+    echo "$BASENAME in $DIR"
 # note: above will break with trailing slash
-	echo "$(date) Compressing local codebase backup."
-	tar -czvf "$BASENAME.tgz" -C "$DIR" "$BASENAME" --remove-files
-	[ ! $? -eq 0  ] && notify "File compression error for ${DOMAIN}" critical
+    echo "$(date) Compressing local codebase backup."
+    tar -czvf "$BASENAME.tgz" -C "$DIR" "$BASENAME" --remove-files
+    [ ! $? -eq 0  ] && notify "File compression error for ${DOMAIN}" critical
 }
 
 backup-full() {
-	$RESTIC backup --cache-dir ${RESTIC_CACHE} ${FULLBUPDIR}/ --tag ${DOMAIN}
-	[ ! $? -eq 0  ] && notify "Restic error for ${DOMAIN}" critical
+    $RESTIC backup --cache-dir ${RESTIC_CACHE} ${FULLBUPDIR}/ --tag ${DOMAIN}
+    [ ! $? -eq 0  ] && notify "Restic error for ${DOMAIN}" critical
 }
 
 backup-db() {
-	$RESTIC backup --cache-dir ${RESTIC_CACHE} ${DBFNAME}.gz --tag ${DOMAIN}
-	[ ! $? -eq 0  ] && notify "Restic error ${DOMAIN}" critical
+    $RESTIC backup --cache-dir ${RESTIC_CACHE} ${DBFNAME}.gz --tag ${DOMAIN}
+    [ ! $? -eq 0  ] && notify "Restic error ${DOMAIN}" critical
 }
 
 set-permissions() {
-	if [ -z "$3" ]; then
-		wordpress-permissions "$DOMAIN" dev
-	fi
+    if [ -z "$3" ]; then
+        wordpress-permissions "$DOMAIN" dev
+    fi
 }
 
 set-permissions "$@"
@@ -258,34 +258,34 @@ wp-check
 echo "$(date) Proceeding with backup for ${DOMAIN}."
 
 if [ ${BACKUPTYPE} = "db" ]; then
-	echo "$(date) Database backup, skipping full sync."
-	rotate-db-backups
-	dump-db
+    echo "$(date) Database backup, skipping full sync."
+    rotate-db-backups
+    dump-db
 elif [ ${BACKUPTYPE} = "tmp" ]; then
-	echo "$(date) Backup db and codebase to /tmp, skipping restic."
-	echo "$(date) This backup will not be written to s3."
-	dump-db
-	sync-files
+    echo "$(date) Backup db and codebase to /tmp, skipping restic."
+    echo "$(date) This backup will not be written to s3."
+    dump-db
+    sync-files
 elif [ ${BACKUPTYPE} = "dbtmp" ]; then
-	echo "$(date) Backup db to /tmp, skipping restic."
-	echo "$(date) This backup will not be written to s3."
-	dump-db
+    echo "$(date) Backup db to /tmp, skipping restic."
+    echo "$(date) This backup will not be written to s3."
+    dump-db
 elif [ ${BACKUPTYPE} = "manual" ]; then
-	restic-check
-	dump-db
-	backup-db
-	sync-files
-	backup-full
-	compress_codebase
-	notify "Backup (${BACKUPTYPE}) completed for ${SITEURL}."
+    restic-check
+    dump-db
+    backup-db
+    sync-files
+    backup-full
+    compress_codebase
+    notify "Backup (${BACKUPTYPE}) completed for ${SITEURL}."
 else
-	restic-check
-	rotate-db-backups
-	dump-db
-	backup-db
-	sync-files
-	backup-full
-	notify "Backup (${BACKUPTYPE}) completed for ${SITEURL}."
+    restic-check
+    rotate-db-backups
+    dump-db
+    backup-db
+    sync-files
+    backup-full
+    notify "Backup (${BACKUPTYPE}) completed for ${SITEURL}."
 fi
 
 exit 0
diff --git a/wordpress-deploy b/wordpress-deploy
--- a/wordpress-deploy
+++ b/wordpress-deploy
@@ -19,91 +19,91 @@ with OWNER as the argument unless OWNER is set to \"none\".
 
 Requires a .gitignore file in worktree dir to use as file mask.
 Deletes all files in WEBROOT unless they exist:
-	a) in the worktree
-	b) in the .gitignore
+    a) in the worktree
+    b) in the .gitignore
 A discouraging robots.txt is added to WEBROOT when the
 git branch is detected to be staging or development.
 "
 # Print USAGE if no args
 if [ $# -eq 0 ]; then
-	echo "$USAGE"
-	exit 1
+    echo "$USAGE"
+    exit 1
 fi
 if [ ! $(which notify) ]; then
-	echo "$(date) notify-cli not found, exiting"
-	exit 1
+    echo "$(date) notify-cli not found, exiting"
+    exit 1
 fi
 
 # msgfmt formats notification content
 msgfmt() {
-	local s
-	case $1 in
-	init)
-		s="wordpress-deploy is running"
-	;;
-	path)
-		s="\`wp-cli\` not found on admin server"
-	;;
-	gitignore)
-		s="gitignore not found in $WORKTREE"
-	;;
-	syncdoing)
-		s="syncing files to ${DOMAIN}:${WEBROOT}"
-	;;
-	syncgood)
-		s="rsync completed without error"
-	;;
-	rsync23)
-		s="rsync exited with code 23 (some files failed to transfer)"
-	;;
-	rsync)
-		s="rsync exited with code $ERR"
-	;;
-	branch)
-		s="Branch detection error"
-	;;
-	botslocate)
-		s="Could not locate the $ROBOTSTXT template"
-	;;
-	botsdeploy)
-		s="$BRANCH branch, disallow all bots"
-	;;
-	botserror)
-		s="rsync error  while deploying $ROBOTSTXT"
-	;;
-	botsexist)
-		s="Robots.txt exists on production domain $SITEURL"
-	;;
-	botsactual)
-		s="Actual robots.txt after deployment: $ROBOTSREAL"
-	;;
-	botscurl)
-		s="Curl failed to retrieve robots.txt with error code $ERR"
-	;;
-	botssuccess)
-		s="rsync completed without error (for $ROBOTSTXT)"
-	;;
-	nowp)
-		s="\`wp core is-installed\` failed, most likely a PATH issue"
-	;;
-	siteurl)
-		s="Error getting siteurl, using ssh HOST"
-	;;
-	perms)
-		s="wordpress-permissions exited with code $ERR"
-	;;
-	fin)
-		s="Deployment completed
+    local s
+    case $1 in
+    init)
+        s="wordpress-deploy is running"
+    ;;
+    path)
+        s="\`wp-cli\` not found on admin server"
+    ;;
+    gitignore)
+        s="gitignore not found in $WORKTREE"
+    ;;
+    syncdoing)
+        s="syncing files to ${DOMAIN}:${WEBROOT}"
+    ;;
+    syncgood)
+        s="rsync completed without error"
+    ;;
+    rsync23)
+        s="rsync exited with code 23 (some files failed to transfer)"
+    ;;
+    rsync)
+        s="rsync exited with code $ERR"
+    ;;
+    branch)
+        s="Branch detection error"
+    ;;
+    botslocate)
+        s="Could not locate the $ROBOTSTXT template"
+    ;;
+    botsdeploy)
+        s="$BRANCH branch, disallow all bots"
+    ;;
+    botserror)
+        s="rsync error  while deploying $ROBOTSTXT"
+    ;;
+    botsexist)
+        s="Robots.txt exists on production domain $SITEURL"
+    ;;
+    botsactual)
+        s="Actual robots.txt after deployment: $ROBOTSREAL"
+    ;;
+    botscurl)
+        s="Curl failed to retrieve robots.txt with error code $ERR"
+    ;;
+    botssuccess)
+        s="rsync completed without error (for $ROBOTSTXT)"
+    ;;
+    nowp)
+        s="\`wp core is-installed\` failed, most likely a PATH issue"
+    ;;
+    siteurl)
+        s="Error getting siteurl, using ssh HOST"
+    ;;
+    perms)
+        s="wordpress-permissions exited with code $ERR"
+    ;;
+    fin)
+        s="Deployment completed
 ____________________"
-	;;
-	nopush)
-		s="Use this command to force deployment without pushing:
+    ;;
+    nopush)
+        s="Use this command to force deployment without pushing:
 \`\`\`
 ssh developer@adminserver.example.com -p 22 -f \"$REPO/hooks/post-receive nocheckout\"
 \`\`\`"
-	;;
-	esac
-	notify "$s" $2
+    ;;
+    esac
+    notify "$s" $2
 }
 
 SCRIPTDIR="$( cd "$( dirname "$(readlink -f "$0")" )" >/dev/null 2>&1 && pwd )"
@@ -129,119 +129,119 @@ ROBOTSTXT=""
 ROBOTSREAL=""
 WPBIN=$(which wp)
 if [ $? -eq 0 ]; then
-	WP="$WPBIN --path=$WEBROOT --allow-root --skip-themes --skip-plugins --ssh=$DOMAIN"
+    WP="$WPBIN --path=$WEBROOT --allow-root --skip-themes --skip-plugins --ssh=$DOMAIN"
 else
-	msgfmt 'path' critical
-	exit 1
+    msgfmt 'path' critical
+    exit 1
 fi
 
 msgfmt 'init'
 
 
 check_for_gitignore() {
-	if [ ! -f "$GITIGNORE" ]; then 
-		msgfmt 'gitignore' critical
-		exit 1
-	fi
+    if [ ! -f "$GITIGNORE" ]; then 
+        msgfmt 'gitignore' critical
+        exit 1
+    fi
 }
 
 do_the_sync() {
-	msgfmt 'syncdoing' log
-	rsync -r \
-		--exclude=".git*" \
-		--exclude-from="$GITIGNORE" \
-		--delete \
-		--chmod=D755,F644 \
-		$WORKTREE/ ${DOMAIN}:${WEBROOT}
-	ERR="$?"
-	if [ "$ERR" -eq 23 ]; then
-		msgfmt 'rsync23'  log
-	elif [ ! "$ERR" -eq 0 ]; then
-		msgfmt 'rsync' critical
-		msgfmt 'nopush' critical
-	else
-		msgfmt 'syncgood' log
-	fi
+    msgfmt 'syncdoing' log
+    rsync -r \
+        --exclude=".git*" \
+        --exclude-from="$GITIGNORE" \
+        --delete \
+        --chmod=D755,F644 \
+        $WORKTREE/ ${DOMAIN}:${WEBROOT}
+    ERR="$?"
+    if [ "$ERR" -eq 23 ]; then
+        msgfmt 'rsync23'  log
+    elif [ ! "$ERR" -eq 0 ]; then
+        msgfmt 'rsync' critical
+        msgfmt 'nopush' critical
+    else
+        msgfmt 'syncgood' log
+    fi
 }
 
 forbid_robots() {
-	cd "$REPO"
-	BRANCH="$(git rev-parse --abbrev-ref HEAD)"
-	if [ ! $? -eq 0 ]; then
-		msgfmt 'branch' critical
-	fi
+    cd "$REPO"
+    BRANCH="$(git rev-parse --abbrev-ref HEAD)"
+    if [ ! $? -eq 0 ]; then
+        msgfmt 'branch' critical
+    fi
 
-	if [[ "$BRANCH" == "staging" ]] \
-	|| [[ "$BRANCH" == "development" ]]
-	then
-		deploy_robots
-	elif [[ "$BRANCH" == "master" ]] \
-	|| [[ "$BRANCH" == "main" ]]
-	then
-		production_robots
-	fi
-	get_robots
+    if [[ "$BRANCH" == "staging" ]] \
+    || [[ "$BRANCH" == "development" ]]
+    then
+        deploy_robots
+    elif [[ "$BRANCH" == "master" ]] \
+    || [[ "$BRANCH" == "main" ]]
+    then
+        production_robots
+    fi
+    get_robots
 }
 
 deploy_robots() {
-	ROBOTSTXT="$SCRIPTDIR/robots.txt-disallow"
-	if [ ! -f "$ROBOTSTXT" ]; then
-		msgfmt 'botslocate' critical
-		exit 1
-	fi
-	msgfmt 'botsdeploy' log
-	rsync -v "$ROBOTSTXT" "${DOMAIN}:${WEBROOT}/robots.txt"
-	if [ ! $? -eq 0 ]; then
-		msgfmt 'boterr' critical
-	else
-		msgfmt 'botssuccess' log
-	fi
+    ROBOTSTXT="$SCRIPTDIR/robots.txt-disallow"
+    if [ ! -f "$ROBOTSTXT" ]; then
+        msgfmt 'botslocate' critical
+        exit 1
+    fi
+    msgfmt 'botsdeploy' log
+    rsync -v "$ROBOTSTXT" "${DOMAIN}:${WEBROOT}/robots.txt"
+    if [ ! $? -eq 0 ]; then
+        msgfmt 'boterr' critical
+    else
+        msgfmt 'botssuccess' log
+    fi
 }
 
 production_robots() {
-	ssh $DOMAIN "[ -f $WEBROOT/robots.txt ] && exit 42" > /dev/null 2>&1
-	if [ $? -eq 42 ]; then
-		msgfmt 'botsexist' critical
-	fi
+    ssh $DOMAIN "[ -f $WEBROOT/robots.txt ] && exit 42" > /dev/null 2>&1
+    if [ $? -eq 42 ]; then
+        msgfmt 'botsexist' critical
+    fi
 }
 
 get_robots() {
-	CURLTMP="/tmp/curl-$(date +%s).tmp"
-	curl --insecure $SITEURL/robots.txt > $CURLTMP
-	ERR="$?"
-	ROBOTSREAL="$(cat $CURLTMP)"
-	if [ $ERR -eq 0 ] && [ ! -z "$ROBOTSREAL" ]; then
-		ROBOTSREAL="\`\`\`$ROBOTSREAL\`\`\`"
-		msgfmt 'botsactual'
-	else
-		msgfmt 'botscurl' critical
-	fi
-	rm $CURLTMP
+    CURLTMP="/tmp/curl-$(date +%s).tmp"
+    curl --insecure $SITEURL/robots.txt > $CURLTMP
+    ERR="$?"
+    ROBOTSREAL="$(cat $CURLTMP)"
+    if [ $ERR -eq 0 ] && [ ! -z "$ROBOTSREAL" ]; then
+        ROBOTSREAL="\`\`\`$ROBOTSREAL\`\`\`"
+        msgfmt 'botsactual'
+    else
+        msgfmt 'botscurl' critical
+    fi
+    rm $CURLTMP
 }
 
 set_permissions() {
-	if [[ "$OWNER" != "none" ]]; then
-		wordpress-permissions "$DOMAIN" "$OWNER"
-		ERR="$?"
-		if [ ! "$ERR" -eq 0 ]; then
-			msgfmt 'perms' critical
-		fi
-	fi
+    if [[ "$OWNER" != "none" ]]; then
+        wordpress-permissions "$DOMAIN" "$OWNER"
+        ERR="$?"
+        if [ ! "$ERR" -eq 0 ]; then
+            msgfmt 'perms' critical
+        fi
+    fi
 }
 
 check_installed() {
-	$WP --quiet core is-installed
-	if [ ! $? -eq 0 ]; then
-		msgfmt 'nowp' critical
-	fi
+    $WP --quiet core is-installed
+    if [ ! $? -eq 0 ]; then
+        msgfmt 'nowp' critical
+    fi
 }
 
 get_siteurl() {
-	SITEURL=$($WP --quiet option get siteurl)
-	if [ ! $? -eq 0 ]; then
-		msgfmt 'siteurl' critical
-		SITEURL="https://$DOMAIN/"
-	fi
+    SITEURL=$($WP --quiet option get siteurl)
+    if [ ! $? -eq 0 ]; then
+        msgfmt 'siteurl' critical
+        SITEURL="https://$DOMAIN/"
+    fi
 }
 
 
