Error checking etc

diff --git a/wordpress-backup b/wordpress-backup
--- a/wordpress-backup
+++ b/wordpress-backup
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+args="--path=/var/www/html"
+target=${1}.sql
+backupDir="/var/backups/wordpress"
+backupsToKeep=28
+
 # Check if there is a first argument
 if [  ${1+x} ]; then
 	if [ $1 == "daily" ] || [ $1 == "hourly" ] || [ $1 == "manual" ] || [ $1 == "tmp" ]; then
@@ -11,7 +16,6 @@ else
 	exit 1
 fi
 
-args="--path=/var/www/html"
 # See wordpress-list for explanation of this code:
 ssh -q ${1} "\
 	[ -f /usr/local/bin/wp ] \
@@ -22,12 +26,9 @@ if [ ! $? -eq 0 ]; then
 	exit 1
 fi
 
-target=${1}.sql
-backupDir="/var/backups/wordpress"
-
 function rotate()
 {
-	i="24"
+	i=$backupsToKeep
 	while [ $i -gt 0 ]
 	do
 		if [ $i -gt 1 ]; then
@@ -58,12 +59,16 @@ else
 	rotate $1
 fi
 
-args="--path=/var/www/html"
-ssh ${1} "\
-	wp ${args} db export /var/www/${target}; \
-	gzip -vf /var/www/${target}"
+ssh ${1} "wp ${args} db export /var/www/${target}"
+if [ ! $? -eq 0  ]; then
+	echo $(date) "Backup export failed for ${1} (${2})" 
+	exit 1
+fi
+ssh ${1} "gzip -vf /var/www/${target}"
+if [ ! $? -eq 0  ]; then
+	echo $(date) "Backup gzip failed for ${1} (${2})" 
+	exit 1
+fi
 scp ${1}:/var/www/${target}.gz .
-
 echo $(date) "Backup completed for ${1} (${2})" 
-
 exit 0
