Docs

diff --git a/wordpress-list b/wordpress-list
--- a/wordpress-list
+++ b/wordpress-list
@@ -1,17 +1,28 @@
 #!/bin/bash
+
+# Fancy way to read a file line by line from stack overflow
+# The file is read in at the bottom of the loop
 while IFS='' read -r line || [[ -n "$line" ]]; do
+    # Look for lines with "Host "
     if [[ $line == *"Host "* ]]; then
+        # Strip the label and trailing space
         host="${line#Host *}"
         args="--path=/var/www/html"
+	# The remote command is a conditional: if wp is found then execute, or exit status 1
+        # The < /dev/null is needed to keep ssh from reading the rest of script as stdin
         ssh -q ${host} "\
 		[ -f /usr/local/bin/wp ] \
 		&& wp --quiet $args core is-installed \
 		|| exit 1" < /dev/null
+        # The $? variable stores the exit status of the last command
+        # ssh outputs the exit status of the remote command 
+        # The 'wp core is-installed' command returns an exit status of 0 or 1
+        # So, if $? does not equal zero, the host does not have a wordpress site
 	if [ $? -eq 0 ]; then
 		echo ${host}
 	fi
     fi
 done < ~/.ssh/config
-
+# The file contents are piped in from the end of the loop, for some reason this works best
 
 exit 0
