Ask permission before importing db

diff --git a/wordpress-restore b/wordpress-restore
--- a/wordpress-restore
+++ b/wordpress-restore
@@ -106,8 +106,11 @@ function main {
     scp "$DB" "${FQDN}:/var/www/restore.sql" || { echo "scp error"; exit 1; }
     trap "rm ${DB}" EXIT
     wp $WPARGS db reset
-    wp $WPARGS db import /var/www/restore.sql
-    [ ! $? -eq 0 ] && { echo "Db import error"; exit 1; }
+    read -p "Import the database? (y/n) " -n 1 -r
+    if [[ $REPLY =~ ^[Yy]$ ]]; then
+        wp $WPARGS db import /var/www/restore.sql
+        [ ! $? -eq 0 ] && { echo "Db import error"; exit 1; }
+    fi
     SITEURL=$(wp $WPARGS option get siteurl)
     [ ! $? -eq 0 ] && { echo "Siteurl error"; exit 1; }
 
