Working better

diff --git a/wordpress-list b/wordpress-list
--- a/wordpress-list
+++ b/wordpress-list
@@ -1,21 +1,20 @@
 #!/bin/bash
 main()
 {
-	params="-o ConnectTimeout=yy1 -o ConnectionAttempts=1"
+	params="-o ConnectTimeout=1 -o ConnectionAttempts=1"
 	args="--path=/var/www/html"
 	while IFS='' read -r line || [[ -n "$line" ]]; do
 		if [[ $line == *"Host "* ]]; then
 			host="${line#Host *}"
-			ssh ${params} -q ${host} "\
-				[ -f /usr/local/bin/wp ] \
-				&& wp --quiet $args core is-installed \
+			ssh ${params} -q ${host} "[ -f /usr/local/bin/wp ] \
+				&& wp --quiet ${args} core is-installed \
 				|| exit 1" < /dev/null
 			if [ $? -eq 0 ]; then
 				echo ${host}
 			else 
 				continue
 			fi
-			if [ $1 == "-v" ]; then
+			if [ "$1" == "-v" ]; then
 				version=$(ssh ${params} ${host} "wp ${args} core version")
 				echo ${version}
 			fi
@@ -24,8 +23,7 @@ main()
 }
 abort()
 {
-	echo "An error occurred. Exiting..." >&2
-	exit 1
+	echo "error" >&2
 }
 trap 'abort' 0
 set -e
