s/HOSTNAME/DOMAIN

diff --git a/wordpress-backup b/wordpress-backup
--- a/wordpress-backup
+++ b/wordpress-backup
@@ -2,9 +2,9 @@
 USAGE="
 $(basename $0) Version  0.2.8
 
-Usage: wordpress-backup HOSTNAME BACKUPTYPE [WEBROOT]
+Usage: wordpress-backup DOMAIN BACKUPTYPE [WEBROOT]
 Where:
-- HOSTNAME must be available in ssh config
+- DOMAIN must be available in ssh config
 - BACKUPTYPE can be one of:
 	- full: backup webroot and db to s3, rotated
 	- manual: full backup to BACKUP_DIRECTORY_LOCAL/manual and s3, not rotated
@@ -48,12 +48,12 @@ fi
 # Remove the lockdir on exit
 trap 'rm -rf /tmp/wordpress-backup.lock' EXIT	
 
-HOSTNAME="$1"
+DOMAIN="$1"
 GROUP="mribackup"
 # Set defaults if arguments absent
 BACKUPTYPE="${2:-manual}"
 WEBROOT="${3:-/var/www/html}"
-DBFNAME="${HOSTNAME}.sql"
+DBFNAME="${DOMAIN}.sql"
 EXCLUDE="sites/default/files/legacy"
 # Below can optionally be set as environment variables
 BACKUP_DIRECTORY_LOCAL="${BACKUP_DIRECTORY_LOCAL:-/var/backups/wordpress}"
@@ -63,12 +63,12 @@ RESTIC_CACHE=${RESTIC_CACHE:-~/.cache/restic}
 # Initialize other variables
 FULLBUPDIR=""
 SITEURL=""
-TEASER="${HOSTNAME} (${BACKUPTYPE}) at ${SITEURL}"
+TEASER="${DOMAIN} (${BACKUPTYPE}) at ${SITEURL}"
 # Find the wp-cli binary
 WPBIN=$(which wp)
 # Set global options for wp-cli or report missing binary
 if [ $? -eq 0 ]; then
-	WP="${WPBIN} --path=${WEBROOT} --allow-root --skip-themes --skip-plugins --ssh=${HOSTNAME}"
+	WP="${WPBIN} --path=${WEBROOT} --allow-root --skip-themes --skip-plugins --ssh=${DOMAIN}"
 else
 	notify "wp-cli not found on admin server" critical
 	exit 1
@@ -87,7 +87,7 @@ restic-check() {
 		fi
 	else
 		notify \
-			"Restic or wp-admin.conf file not found for ${USER}@${HOSTNAME}, backup to s3 for ${HOSTNAME} is not happening." critical
+			"Restic or wp-admin.conf file not found for ${USER}@${DOMAIN}, backup to s3 for ${DOMAIN} is not happening." critical
 	fi
 }
 
@@ -97,14 +97,14 @@ wp-check() {
 		--quiet \
 		core is-installed
 	if [ ! $? -eq 0 ]; then
-		notify "${HOSTNAME} \
+		notify "${DOMAIN} \
 			WP does not appear to be running. What the heck?" \
 			critical
 		exit 1
 	fi
 	SITEURL=$(${WP} --quiet option get siteurl)
 	if [ ! $? -eq 0 ]; then
-		notify "${HOSTNAME} \
+		notify "${DOMAIN} \
 			Error getting siteurl." \
 			critical
 		exit 1
@@ -113,11 +113,11 @@ wp-check() {
 }
 
 check-args() {
-	if [ "$HOSTNAME" == "full" ] \
-		|| [ "$HOSTNAME" == "db" ] \
-		|| [ "$HOSTNAME" == "manual" ] \
-		|| [ "$HOSTNAME" == "tmp" ]; then
-		notify "Error in first argument, ${HOSTNAME} (arg1) ${BACKUPTYPE} (arg 2) backup." critical
+	if [ "$DOMAIN" == "full" ] \
+		|| [ "$DOMAIN" == "db" ] \
+		|| [ "$DOMAIN" == "manual" ] \
+		|| [ "$DOMAIN" == "tmp" ]; then
+		notify "Error in first argument, ${DOMAIN} (arg1) ${BACKUPTYPE} (arg 2) backup." critical
 		exit 1
 	fi
 	if [ "$BACKUPTYPE" != "full" ] \
@@ -125,7 +125,7 @@ check-args() {
 		&& [ "$BACKUPTYPE" != "manual" ] \
 		&& [ "$BACKUPTYPE" != "tmp" ] \
 		&& [ "$BACKUPTYPE" != "dbtmp" ]; then
-		notify "Error in second argument, ${HOSTNAME} (arg 1) ${BACKUPTYPE} (arg 2) backup." critical
+		notify "Error in second argument, ${DOMAIN} (arg 1) ${BACKUPTYPE} (arg 2) backup." critical
 		exit 1
 	fi
 }
@@ -133,20 +133,20 @@ check-args() {
 set-backup-dir() {
 	case "$BACKUPTYPE" in
 	"db") 
-		DBFNAME=${HOSTNAME}-dbonly.sql
+		DBFNAME=${DOMAIN}-dbonly.sql
 		;;
 	"manual") 
 		local DATESTAMP=$(date +%F)
-		DBFNAME="${HOSTNAME}-${DATESTAMP}.sql"
+		DBFNAME="${DOMAIN}-${DATESTAMP}.sql"
 		BACKUP_DIRECTORY_LOCAL="${BACKUP_DIRECTORY_LOCAL}/manual"
-		FULLBUPDIR="${BACKUP_DIRECTORY_LOCAL}/${HOSTNAME}-${DATESTAMP}"
+		FULLBUPDIR="${BACKUP_DIRECTORY_LOCAL}/${DOMAIN}-${DATESTAMP}"
 		;;
 	"full") 
-		FULLBUPDIR="${BACKUP_DIRECTORY_LOCAL}/${HOSTNAME}"
+		FULLBUPDIR="${BACKUP_DIRECTORY_LOCAL}/${DOMAIN}"
 		;;
 	"tmp") 
 		BACKUP_DIRECTORY_LOCAL="/tmp"
-		FULLBUPDIR="${BACKUP_DIRECTORY_LOCAL}/${HOSTNAME}"
+		FULLBUPDIR="${BACKUP_DIRECTORY_LOCAL}/${DOMAIN}"
 		;;
 	"dbtmp")
 		BACKUP_DIRECTORY_LOCAL="/tmp"
@@ -188,12 +188,12 @@ dump-db() {
 		notify "Database export failed for ${TEASER}" critical
 		exit 1
 	fi
-	ssh ${HOSTNAME} "gzip -vf ${WEBROOT}/../${DBFNAME}"
+	ssh ${DOMAIN} "gzip -vf ${WEBROOT}/../${DBFNAME}"
 	if [ ! $? -eq 0  ]; then
 		notify "Backup gzip failed for ${TEASER}" critical
 		exit 1
 	fi
-	scp ${HOSTNAME}:${WEBROOT}/../${DBFNAME}.gz .
+	scp ${DOMAIN}:${WEBROOT}/../${DBFNAME}.gz .
 	if [ ! $? -eq 0  ]; then
 		notify "DB scp failed for ${TEASER}" critical
 		exit 1
@@ -202,15 +202,15 @@ dump-db() {
 
 sync-files() {
 	[ ! -d $FULLBUPDIR ] && mkdir $FULLBUPDIR
-	echo "$(date) Sync codebase from ${HOSTNAME}"
+	echo "$(date) Sync codebase from ${DOMAIN}"
 	rsync \
 		-qptLr \
 		--exclude=${EXCLUDE} \
 		--delete \
-		${HOSTNAME}:${WEBROOT} \
+		${DOMAIN}:${WEBROOT} \
 		${FULLBUPDIR}
 	if [ $? -eq 0 ]; then
-		echo "$(date) Sync from ${HOSTNAME} was completed without error"
+		echo "$(date) Sync from ${DOMAIN} was completed without error"
 	else
 		notify "File sync failed for ${TEASER}" critical
 	fi
@@ -227,22 +227,22 @@ compress_codebase() {
 # note: above will break with trailing slash
 	echo "$(date) Compressing local codebase backup."
 	tar -czvf "$BASENAME.tgz" -C "$DIR" "$BASENAME" --remove-files
-	[ ! $? -eq 0  ] && notify "File compression error for ${HOSTNAME}" critical
+	[ ! $? -eq 0  ] && notify "File compression error for ${DOMAIN}" critical
 }
 
 backup-full() {
-	$RESTIC backup --cache-dir ${RESTIC_CACHE} ${FULLBUPDIR}/ --tag ${HOSTNAME}
-	[ ! $? -eq 0  ] && notify "Restic error for ${HOSTNAME}" critical
+	$RESTIC backup --cache-dir ${RESTIC_CACHE} ${FULLBUPDIR}/ --tag ${DOMAIN}
+	[ ! $? -eq 0  ] && notify "Restic error for ${DOMAIN}" critical
 }
 
 backup-db() {
-	$RESTIC backup --cache-dir ${RESTIC_CACHE} ${DBFNAME}.gz --tag ${HOSTNAME}
-	[ ! $? -eq 0  ] && notify "Restic error ${HOSTNAME}" critical
+	$RESTIC backup --cache-dir ${RESTIC_CACHE} ${DBFNAME}.gz --tag ${DOMAIN}
+	[ ! $? -eq 0  ] && notify "Restic error ${DOMAIN}" critical
 }
 
 set-permissions() {
 	if [ -z "$3" ]; then
-		wordpress-permissions "$HOSTNAME" dev
+		wordpress-permissions "$DOMAIN" dev
 	fi
 }
 
@@ -250,7 +250,7 @@ set-permissions "$@"
 check-args 
 set-backup-dir
 wp-check
-echo "$(date) Proceeding with backup for ${HOSTNAME}."
+echo "$(date) Proceeding with backup for ${DOMAIN}."
 
 if [ ${BACKUPTYPE} = "db" ]; then
 	echo "$(date) Database backup, skipping full sync."
