Adding tests and checks

diff --git a/wordpress-backup b/wordpress-backup
--- a/wordpress-backup
+++ b/wordpress-backup
@@ -1,5 +1,16 @@
 #!/bin/bash
 
+# Check if there is a first argument
+if [  ${1+x} ]; then
+	if [ $1 == "daily" ] || [ $1 == "hourly" ] || [ $1 == "manual" ] || [ $1 == "tmp" ]; then
+		echo "Error in first argument."
+		exit 1
+	fi
+else
+	echo "Missing first argument."
+	exit 1
+fi
+
 args="--path=/var/www/html"
 # See wordpress-list for explanation of this code:
 ssh -q ${1} "\
diff --git a/wordpress-restore b/wordpress-restore
--- a/wordpress-restore
+++ b/wordpress-restore
@@ -1,15 +1,17 @@
 #!/bin/bash
-# Next line checks if there is a first argument
-if [ ! ${1+x} ]; then
-	echo "Missing first argument."
-	exit 1
-else
+
+# Check if there is a first argument
+if [  ${1+x} ]; then
 	if [ $1 == "daily" ] || [ $1 == "hourly" ] || [ $1 == "manual" ] || [ $1 == "tmp" ]; then
 		echo "Error in first argument."
 		exit 1
 	fi
+else
+	echo "Missing first argument."
+	exit 1
 fi
-# Next line checks if there is a second argument
+
+# Check if there is a second argument
 if [ ${2+x} ]; then
 	if [ $2 == "daily" ] || [ $2 == "hourly" ] || [ $2 == "manual" ]; then
 		echo "Salright"
@@ -19,6 +21,18 @@ if [ ${2+x} ]; then
 	fi
 else
 	echo "Missing second argument."
+	exit 1
+fi
+
+# Check if WordPress is actually running
+# See wordpress-list for explanation of this code:
+args="--path=/var/www/html"
+ssh -q ${1} "\
+	[ -f /usr/local/bin/wp ] \
+	&& wp --quiet $args core is-installed \
+	|| exit 1" < /dev/null
+if [ ! $? -eq 0 ]; then
+	echo "${1} is not online. Proceed manually."
 	exit 1
 fi
 
