Check for notify-cli

diff --git a/wordpress-deploy b/wordpress-deploy
--- a/wordpress-deploy
+++ b/wordpress-deploy
@@ -29,6 +29,10 @@ if [ $# -eq 0 ]; then
 	echo "$USAGE"
 	exit 1
 fi
+if [ ! $(which notify) ]; then
+	echo "$(date) notify-cli not found, exiting"
+	exit 1
+fi
 
 export SLACK_CHANNEL_NORMAL="__deploy"
 export SLACK_CHANNEL_CRITICAL="__error"
