Test for webroot before setting permissions

diff --git a/wordpress-permissions b/wordpress-permissions
--- a/wordpress-permissions
+++ b/wordpress-permissions
@@ -27,20 +27,27 @@ else
 	OWNER=${2}
 fi
 WEBROOT="${3:-/var/www/html}"
-ssh ${1} "sudo chown -R ${OWNER}:www-data ${WEBROOT};"
-ssh ${1} "sudo chown ${OWNER}:www-data ${WEBROOT}/..;"
-ssh ${1} "sudo chown root:www-data ${WEBROOT}/wp-config.php;"
-ssh ${1} "[ -d ${WEBROOT}/wp-content/uploads ] && \
-    sudo chown -R www-data:${OWNER} ${WEBROOT}/wp-content/uploads; \
-    [ -d ${WEBROOT}/wp-content/banners ] && \
-    sudo chown -R www-data:${OWNER} ${WEBROOT}/wp-content/banners; \
-    [ -d ${WEBROOT}/wp-content/plugins/wpspx-master/cache ] && \
-    sudo chown -R www-data:${OWNER} ${WEBROOT}/wp-content/plugins/wpspx-master/cache;
-"
-ssh ${1} "[ -d ${WEBROOT}/wp-content/uploads ] && \
-    sudo chmod g+s -R ${WEBROOT}/wp-content;"
-ssh ${1} "sudo find ${WEBROOT} -type f -exec chmod 640 {} +; \
-    sudo find ${WEBROOT} -type d -exec chmod 750 {} +;
-    sudo chmod 644 ${WEBROOT}/wp-config.php;
-"
+ssh "$1" "[ -d ${WEBROOT} ] || exit 1"
+if [ $? -eq 1 ]; then
+    echo "Webroot not found"
+    exit 1
+else
+    ssh "$1" "sudo chown -R ${OWNER}:www-data ${WEBROOT};"
+    ssh "$1" "sudo chown ${OWNER}:www-data ${WEBROOT}/..;"
+    ssh "$1" "sudo chown root:www-data ${WEBROOT}/wp-config.php;"
+    ssh "$1" "[ -d ${WEBROOT}/wp-content/uploads ] && \
+        sudo chown -R www-data:${OWNER} ${WEBROOT}/wp-content/uploads; \
+        [ -d ${WEBROOT}/wp-content/banners ] && \
+        sudo chown -R www-data:${OWNER} ${WEBROOT}/wp-content/banners; \
+        [ -d ${WEBROOT}/wp-content/plugins/wpspx-master/cache ] && \
+        sudo chown -R www-data:${OWNER} ${WEBROOT}/wp-content/plugins/wpspx-master/cache;
+    "
+    ssh "$1" "[ -d ${WEBROOT}/wp-content/uploads ] && \
+        sudo chmod g+s -R ${WEBROOT}/wp-content;"
+    ssh "$1" "sudo find ${WEBROOT} -type f -exec chmod 640 {} +; \
+        sudo find ${WEBROOT} -type d -exec chmod 750 {} +;
+        sudo chmod 644 ${WEBROOT}/wp-config.php;
+    "
+    echo "Permissions updated on ${HOSTNAME}"
+fi
 exit 0
