Add fourth arg for siteurl parameter

diff --git a/wordpress-backup b/wordpress-backup
--- a/wordpress-backup
+++ b/wordpress-backup
@@ -24,16 +24,6 @@ else
 	exit 1
 fi
 
-# Look for the wp-cli binary, if found then run test to see if wp installed
-ssh -q ${1} "\
-	[ -f /usr/local/bin/wp ] \
-	&& wp --quiet $args core is-installed \
-	|| exit 1" < /dev/null
-if [ ! $? -eq 0 ]; then
-	notify-critical "${1} is not online. What the heck?"
-	exit 1
-fi
-siteurl=$(ssh ${1} "wp $args option get siteurl")
 function rotate()
 {
 	i=$backupsToKeep
@@ -48,6 +38,7 @@ function rotate()
 		(( i-- ))
 	done
 }
+
 # Next line checks if there is a second argument
 if [ ${2+x} ]; then
 	if [ $2 == "daily" ]; then
@@ -66,6 +57,21 @@ else
 	cd ${backupDir}/manual
 	rotate $1
 fi
+
+# Look for the wp-cli binary, if found then run test to see if wp installed
+if [ ${2} != "dreamhost" ]; then
+	ssh -q ${1} "\
+		[ -f /usr/local/bin/wp ] \
+		&& wp --quiet $args core is-installed \
+		|| exit 1" < /dev/null
+	if [ ! $? -eq 0 ]; then
+		notify-critical "${1} is not online. What the heck?"
+		exit 1
+	fi
+	siteurl=$(ssh ${1} "wp $args option get siteurl")
+fi
+# Failover to 4th argument for dreamhost:
+siteurl="${siteurl:-$4}"
 
 ssh ${1} "wp --quiet ${args} db export /var/www/${target}"
 if [ ! $? -eq 0  ]; then
